src/Entity/Fonctionement.php
<?php

namespace App\Entity;

use App\Repository\FonctionementRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FonctionementRepository::class)]
class Fonctionement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Module $module = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $createdAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModule(): ?Module
    {
        return $this->module;
    }

    public function setModule(?Module $module): self
    {
        $this->module = $module;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/Mesure.php
<?php

namespace App\Entity;

use App\Repository\MesureRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MesureRepository::class)]
class Mesure
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Module $module = null;

    #[ORM\Column]
    private ?float $value = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModule(): ?Module
    {
        return $this->module;
    }

    public function setModule(?Module $module): self
    {
        $this->module = $module;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Module.php
<?php

namespace App\Entity;

use App\Repository\ModuleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ModuleRepository::class)]
class Module
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $mesure_type = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMesureType(): ?string
    {
        return $this->mesure_type;
    }

    public function setMesureType(string $mesure_type): self
    {
        $this->mesure_type = $mesure_type;

        return $this;
    }
}

src/Controller/ModuleController.php
<?php

namespace App\Controller;

use App\Entity\Module;
use App\Form\ModuleType;
use App\Repository\FonctionementRepository;
use App\Repository\MesureRepository;
use App\Repository\ModuleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ModuleController extends AbstractController
{
    /**
     * @Route("/modules", name="modules_list", methods={"GET"})
     */
    public function index(ModuleRepository $moduleRepository): Response
    {
        $modules = $moduleRepository->findAll();

        return $this->render('module/index.html.twig', [
            'modules' => $modules,
        ]);
    }

    /**
     * @Route("/modules/create", name="module_create", methods={"POST"})
     */
    public function create(Request $request, ModuleRepository $moduleRepository): Response
    {
        try {
            $module = new Module();

            $module->setName($request->request->get('name'));
            $module->setDescription($request->request->get('description'));
            $module->setMesureType($request->request->get('type'));

            $moduleRepository->save($module, true);

            $this->addFlash('success', 'Module créé avec succès.');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Échec de la création du module : ' . $e->getMessage());
        }

        return $this->redirect("/modules");
    }

    /**
     * @Route("/modules/{id}/edit", name="module_edit_view", methods={"GET"})
     */
    public function edit_view(Module $module): Response
    {
        return $this->render('module/edit.html.twig', [
            'module' => $module,
        ]);
    }

    /**
     * @Route("/modules/{id}/edit", name="module_edit", methods={"POST"})
     */
    public function edit(Request $request, Module $module, ModuleRepository $moduleRepository): Response
    {
        try {
            $module->setName($request->request->get('name'));
            $module->setDescription($request->request->get('description'));
            $module->setMesureType($request->request->get('type'));

            $moduleRepository->save($module, true);

            $this->addFlash('success', 'Module mis à jour avec succès.');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Échec de la mise à jour du module : ' . $e->getMessage());
        }

        return $this->redirect("/modules");
    }

    /**
     * @Route("/modules/{id}/delete", name="module_delete", methods={"GET"})
     */
    public function delete(Request $request, Module $module, ModuleRepository $moduleRepository): Response
    {
        try {
            $moduleRepository->remove($module, true);

            $this->addFlash('success', 'Module supprimé avec succès.');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Échec de la suppression du module : ' . $e->getMessage());
        }

        return $this->redirect("/modules");
    }

    /**
     * @Route("/modules/{id}/details", name="module_details", methods={"GET"})
     */
    public function details(Module $module, MesureRepository $mesureRepository, FonctionementRepository $fonctionementRepository): Response
    {
        $mesures = $mesureRepository->findBy([
        'module' => $module
        ]);

        $mesuresData = [];
        foreach ($mesures as $mesure) {
            $mesuresData[] = [
                'createdAt' => $mesure->getCreatedAt()->format('Y-m-d H:i:s'),
                'value' => $mesure->getValue(),
            ];
        }

        $mesures = json_encode($mesuresData);
        
        $fonctionnements = $fonctionementRepository->findBy([
            'module' => $module
        ]);


        return $this->render('module/details.html.twig', [
            'module' => $module,
            'mesures' => $mesures,
            'fonctionnements' => $fonctionnements
        ]);
    }
    /**
        * @Route("/modules", name="modules")
    */
    public function redirectToModules(): Response
    {
        return $this->redirect('/modules');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/module/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Module Detail{% endblock %}

{% block body %}

    {% for flashMessage in app.flashes('success') %}
        <div class="alert alert-success">{{ flashMessage }}</div>
    {% endfor %}
    {% for flashMessage in app.flashes('error') %}
        <div class="alert alert-danger">{{ flashMessage }}</div>
    {% endfor %}

<div class="container p-4">
<a href="/modules" class="btn btn-primary mb-3">Back to Modules</a>
    <h1>Module Details</h1>

    <table class="table table-bordered">
        <tr>
            <th>Name:</th>
            <td>{{ module.name }}</td>
        </tr>
        <tr>
            <th>Description:</th>
            <td>{{ module.description }}</td>
        </tr>
        <tr>
            <th>Mesure Type:</th>
            <td>{{ module.mesureType }}</td>
        </tr>
    </table>

    <a href="/modules/{{ module.id }}/edit" class="btn btn-primary">Edit</a>

    <a href="/modules/{{ module.id }}/delete" class="btn btn-danger">Supprimer</a>


     <div class="mt-5">
        <h3>Module Mesures</h3>
        <canvas id="chart"></canvas>
    </div>

            <h3>Historique de Fonctionnement</h3>
    <table class="table table-bordered mt-5">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for fonctionnement in fonctionnements %}
                    <tr>
                        <td>{{ fonctionnement.getCreatedAt()|date('d m Y') }}</td>
                        <td>
                            {% if fonctionnement.status == 'OK' %}
                                <span class="badge bg-success">{{ fonctionnement.status }}</span>
                            {% elseif fonctionnement.status == 'Failure' %}
                                <span class="badge bg-danger">{{ fonctionnement.status }}</span>
                            {% else %}
                                <span class="badge bg-secondary">{{ fonctionnement.status }}</span></h1>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var measurements = {{ mesures|raw }};
        
        var dates = measurements.map(measure => measure.createdAt);

        var ctx = document.getElementById('chart').getContext('2d');
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: dates,
                datasets: [{
                    label: 'Measurements',
                    data: measurements.map(measure => measure.value),
                    backgroundColor: 'rgba(0, 123, 255, 0.4)',
                    borderColor: 'rgba(0, 123, 255, 1)',
                    borderWidth: 1,
                    pointRadius: 4,
                    pointBackgroundColor: 'rgba(0, 123, 255, 1)',
                    pointBorderColor: '#fff',
                    pointHoverRadius: 6,
                    pointHoverBackgroundColor: '#fff',
                    pointHoverBorderColor: 'rgba(0, 123, 255, 1)',
                }]
            },
            options: {
                scales: {
                    x: {
                        display: true,
                        title: {
                            display: true,
                            text: 'Date'
                        }
                    },
                    y: {
                        display: true,
                        title: {
                            display: true,
                            text: 'Measurement Value'
                        }
                    }
                }
            }
        });
    </script>


</div>

{% endblock %}

templates/module/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Module{% endblock %}

{% block body %}

<div class="container p-4">
    <a href="/modules" class="btn btn-primary mb-3">Back to Modules</a>
    <h1>Module Edit</h1>

    <form action="/modules/{{ module.id }}/edit" method="post">
        <div class="mb-3">
            <label for="name" class="form-label">Nom :</label>
            <input type="text" id="name" name="name" value="{{ module.name }}" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description :</label>
            <textarea id="description" name="description" class="form-control" required>{{ module.description }}</textarea>
        </div>
        <div class="mb-3">
            <label for="type" class="form-label">Type :</label>
            <select id="type" name="type" class="form-select" required>
                <option value="Température" {% if module.mesureType == 'Température' %}selected{% endif %}>Température</option>
                <option value="Vitesse" {% if module.mesureType == 'Vitesse' %}selected{% endif %}>Vitesse</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Modifier</button>
    </form>
</div>

{% endblock %}

templates/module/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modules{% endblock %}

{% block body %}

<div class="container p-4">

  {# Display flash messages #}
    {% for flashMessage in app.flashes('success') %}
        <div class="alert alert-success">{{ flashMessage }}</div>
    {% endfor %}
    {% for flashMessage in app.flashes('error') %}
        <div class="alert alert-danger">{{ flashMessage }}</div>
    {% endfor %}

    <form action="{{ path('module_create') }}" method="POST" class="m-4" >
        <h2>Créer un module</h2>
        <div class="mb-3">
            <label for="name" class="form-label">Nom :</label>
            <input type="text" id="name" name="name" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description :</label>
            <textarea id="description" name="description" class="form-control" required></textarea>
        </div>
        <div class="mb-3">
            <label for="mesure" class="form-label">Type Mesure :</label>
            <select id="mesure" name="type" class="form-select" required>
                <option value="Température">Température</option>  
                <option value="Vitesse">Vitesse</option>  
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Créer</button>
    </form>
    <div>
    
    <h2>Modules existants</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>     
            {% for module in modules %}
                <tr>
                    <td>{{ module.name }}</td>
                    <td>{{ module.description }}</td>
                    <td>{{ module.getMesureType() }}</td>
                    <td>
                        <a href="/modules/{{ module.id }}/edit" class="btn btn-primary">Modifier</a>
                        <a href="/modules/{{ module.id }}/details" class="btn btn-secondary">Details</a>
                        <a href="/modules/{{ module.id }}/delete" class="btn btn-danger">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>

{% endblock %}